import turtle
turtle.shape("turtle")
turtle.Screen().bgcolor('red')
turtle.pencolor("blue")
turtle.circle(60)
turtle.right(90)
turtle.circle(60)
turtle.right(90)
turtle.circle(60)
turtle.right(90)
turtle.circle(60)

turtle.Screen().bgcolor('orange')
turtle.pencolor("yellow")                
turtle.right(40)
turtle.color('yellow')
turtle.right(90)
turtle.circle(40)
turtle.right(90)
turtle.circle(40)
turtle.right(90)
turtle.circle(40)
turtle.right(90)
turtle.circle(40)

turtle.Screen().bgcolor('yellow')
turtle.pencolor("orange")
turtle.color('orange')
turtle.right(90)
turtle.circle(35)
turtle.right(90)
turtle.circle(35)
turtle.right(90)
turtle.circle(35)
turtle.right(90)
turtle.circle(35)

turtle.Screen().bgcolor('green')
turtle.pencolor("red")
turtle.color('red')
turtle.right(90)
turtle.circle(30)
turtle.right(90)
turtle.circle(30)
turtle.right(90)
turtle.circle(30)
turtle.right(90)
turtle.circle(30)
